### ISSUE TITLE
BUG - FoundryVTT 0.8.3 - Cannot add property AIP, object is not extensible

### ISSUE THREAD

**Issue by p4535992** [schultzcole/FVTT-Autocomplete-Inline-Properties#19]
**Environment Details**

Foundry VTT Version: 0.8.3

Operating System: \[Linux\]

How Are You Using Foundry: \[Linux,Native Application (Electron), Chrome\]

Which Game System: Dungeons and Dragons 5th Edition, version 1.3.1

Modules Enabled?: Yes

OS, Hosting, Browser (if applicable): Linux/Node/Chrome

**Description of the issue:**

Not sure but this is probably a retrocompatibility issue with some other module :

![image](https://i.imgur.com/qOTuHE4.png)

**Comment by schultzcole** [comment]
Yeah, this is a new issue introduced in 0.8.3. I'll have to expose the AIP configuration somewhere other than the global `CONFIG` object.

**Comment by schultzcole** [comment]
This should be fixed in Autocomplete Inline Properties 2.0.0, however this is a breaking change. Any modules which used AIP will need to update to maintain compatibility.
