### ISSUE TITLE
Concrete example for adding support via init hook

### ISSUE THREAD

**Issue by dmrickey** [schultzcole/FVTT-Autocomplete-Inline-Properties#8]
I'd like to tinker around with adding support for another system. While the config itself looks straightforward enough, I don't have enough system knowledge to know what the implementation of the callback would look like to add more rules. Could you add an example of something like "For example, if I were to add these dnd5e rules through an init hook it would look like this `code block`"

**Comment by schultzcole** [comment]
Yeah, I'll add an example in CONTRIBUTIONS.md, thanks for the suggestion. I'll let you know when it is pushed.

**Comment by schultzcole** [comment]
Ok, I've added an example [here](https://github.com/schultzcole/FVTT-Autocomplete-Inline-Properties/blob/master/CONTRIBUTING.md#example). You can find more detailed examples of how the configs for dnd5e are set up in package-config.mjs

**Comment by dmrickey** [comment]
Awesome, thanks. That's super helpful
